modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT License"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ecologics"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="decorative_blocks"
    mandatory=false
    versionRange="[2.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersdelight"
    mandatory=false
    versionRange="[1.18.2-1.0.4,]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mcwbridges"
    mandatory=false
    versionRange="[2.0.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="quark"
    mandatory=false
    versionRange="[2.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="autoreglib"
    mandatory=false
    versionRange="[1.7,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
